/**
 * Application Theme Colors and Tokens
 */

const tintColorLight = '#6366F1';
const tintColorDark = '#818CF8';

export const Colors = {
  light: {
    text: '#11181C',
    textPrimary: '#1E1B4B',
    textSecondary: '#64748B',
    textMuted: '#94A3B8',
    background: '#FAFBFF',
    card: '#FFFFFF',
    cardBorder: '#F1F5F9',
    border: '#E2E8F0',
    primary: '#6366F1',
    primaryLight: '#EEF2FF',
    accent: '#8B5CF6',
    surface: '#F8FAFC',
    icon: '#64748B',
    tint: tintColorLight,
    tabBar: '#FFFFFF',
    tabBarBorder: '#E2E8F0',
    tabIconDefault: '#94A3B8',
    tabIconSelected: tintColorLight,
    statusSuccessBg: '#ECFDF5',
    statusSuccessText: '#10B981',
    statusWarningBg: '#FFFBEB',
    statusWarningText: '#F59E0B',
    statusDangerBg: '#FEF2F2',
    statusDangerText: '#EF4444',
  },
  dark: {
    text: '#ECEDEE',
    textPrimary: '#F8FAFC',
    textSecondary: '#CBD5E1',
    textMuted: '#64748B',
    background: '#0B0F19',
    card: '#151D30',
    cardBorder: '#1E293B',
    border: '#334155',
    primary: '#818CF8',
    primaryLight: '#1E1B4B',
    accent: '#A78BFA',
    surface: '#0F172A',
    icon: '#CBD5E1',
    tint: tintColorDark,
    tabBar: '#0F172A',
    tabBarBorder: '#1E293B',
    tabIconDefault: '#64748B',
    tabIconSelected: tintColorDark,
    statusSuccessBg: '#064E3B',
    statusSuccessText: '#34D399',
    statusWarningBg: '#78350F',
    statusWarningText: '#FBBF24',
    statusDangerBg: '#7F1D1D',
    statusDangerText: '#F87171',
  },
  primary: '#6366F1',
  primaryLight: '#EEF2FF',
  background: '#FAFBFF',
  primaryText: '#1E1B4B'
};
