import { Colors } from '@/constants/Colors';
import { StyleSheet } from 'react-native';
export const attendanceScreenStyles = () => {
    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: Colors.background,
        },
        header: {
            flexDirection: 'row',
            justifyContent: 'center',
            alignItems: 'center',
            paddingHorizontal: 20,
            paddingVertical: 16,
            backgroundColor: '#fff',
            borderBottomWidth: 1,
            borderBottomColor: '#e5e7eb',
            paddingBottom: 10,
            paddingTop: 44,
        },
        headerTitle: {
            flex: 1,
            fontSize: 20,
            color: '#242524FF',
            fontWeight: '600',
            textAlign: 'center',
            marginLeft: 10,
        },
        profileAvatar: {
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: Colors.primary,
            alignItems: 'center',
            justifyContent: 'center',
        },
        profileAvatarText: {
            color: '#FFFFFF',
            fontSize: 16,
            fontWeight: '600',
        },
        content: {
            flex: 1,
        },
        dateSection: {
            backgroundColor: '#fff',
            marginHorizontal: 20,
            marginTop: 16,
            borderRadius: 12,
            padding: 16,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 3,
        },
        dateHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            marginBottom: 16,
        },
        dayButton: {
            borderRadius: 20,
            marginHorizontal: 4,
            padding: 8,
            alignItems: 'center',
            justifyContent: 'center',
            minWidth: 36,
            minHeight: 36,
            position: 'relative',
        },
        dayButtonText: {
            fontWeight: '600',
            fontSize: 14,
        },
        todayIndicator: {
            position: 'absolute',
            bottom: 2,
            width: 4,
            height: 4,
            backgroundColor: Colors.primary,
            borderRadius: 2,
        },
        monthYear: {
            fontSize: 16,
            fontFamily: 'Inter-Medium',
            color: '#374151',
        },
        dateSelector: {
            backgroundColor: '#3b82f6',
            borderRadius: 8,
            paddingVertical: 8,
            paddingHorizontal: 16,
            alignSelf: 'center',
        },
        dateText: {
            color: '#fff',
            fontSize: 14,
            fontFamily: 'Inter-Medium',
        },
        averageSection: {
            backgroundColor: '#fff',
            marginHorizontal: 20,
            marginTop: 16,
            borderRadius: 12,
            padding: 20,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 3,
        },
        averageLabel: {
            fontSize: 14,
            fontFamily: 'Inter-Medium',
            color: '#6b7280',
            marginLeft: 6,
        },
        averageTime: {
            fontSize: 28,
            fontFamily: 'Inter-SemiBold',
            color: '#3b82f6',
            marginBottom: 4,
        },
        averageSubtext: {
            fontSize: 12,
            fontFamily: 'Inter-Regular',
            color: '#9ca3af',
        },
        searchContainer: {
            flex: 1,
            paddingVertical: 14,
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
            marginHorizontal: 20,
        },
        searchInputContainer: {
            width: '83%',
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: '#EBEBEAFF',
            borderRadius: 10,
            paddingHorizontal: 12,
            gap: 6,
            borderColor: '#EBEBEAFF',
            borderWidth: 1,
        },
        searchInput: {
            flex: 1,
            fontSize: 16,
            fontFamily: 'Inter-Regular',
            color: '#111827',
        },
        filterButton: {
            padding: 14,
            backgroundColor: '#FFFFFFFF',
            borderWidth: 1,
            borderColor: '#EBEBEAFF',
            borderRadius: 8,
        },
        employeeList: {
            paddingHorizontal: 20,
            paddingTop: 14,
            paddingBottom: 20,
        },
        employeeCard: {
            backgroundColor: '#fff',
            borderRadius: 12,
            padding: 16,
            marginBottom: 12,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 3,
        },
        employeeHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 12,
        },
        employeeInfo: {
            flexDirection: 'row',
            alignItems: 'center',
            flex: 1,
        },
        avatar: {
            width: 48,
            height: 48,
            borderRadius: 24,
            marginRight: 12,
        },
        employeeDetails: {
            flex: 1,
        },
        employeeName: {
            fontSize: 16,
            fontFamily: 'Inter-SemiBold',
            color: '#111827',
            marginBottom: 2,
        },
        employeeDesignation: {
            fontSize: 14,
            fontFamily: 'Inter-Regular',
            color: '#6b7280',
        },
        statusBadge: {
            paddingHorizontal: 12,
            paddingVertical: 6,
            borderRadius: 14,
        },
        statusText: {
            color: '#fff',
            fontSize: 12,
            fontFamily: 'Inter-Medium',
        },
        attendanceInfo: {
            marginBottom: 12,
        },
        timeRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            marginBottom: 8,
        },
        timeItem: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
        },
        durationRow: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        timeLabel: {
            fontSize: 14,
            fontFamily: 'Inter-Regular',
            color: '#6b7280',
            marginRight: 8,
        },
        timeValue: {
            fontSize: 14,
            fontFamily: 'Inter-Medium',
            color: '#111827',
        },
        viewDetailsButton: {
            alignSelf: 'flex-end',
        },
        viewDetailsText: {
            marginTop: 4,
            fontSize: 14,
            fontFamily: 'Inter-Medium',
            color: '#4FC3A2FF',
        },
    });
};