import { Colors } from "@/constants/Colors";
import { StyleSheet } from "react-native";

export const editEmployeeScreenStyles = () => {
    return StyleSheet.create({
        safeArea: {
            flex: 1,
            backgroundColor: '#F8F9FA',
        },
        container: {
            flex: 1,
            backgroundColor: '#F8F9FA',
        },
        header: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 20,
            backgroundColor: '#FFFFFF',
            borderBottomWidth: 1,
            borderBottomColor: '#E5E7EB',
            paddingTop: 12,
            paddingBottom: 8,
            marginBottom: 18,
        },
        backButton: {
            padding: 6,
            marginRight: 4,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#F3F4F6',
            borderRadius: 50,
        },
        headerTitle: {
            fontSize: 16,
            fontWeight: '600',
            color: '#1F2937',
            flex: 1,
            textAlign: 'center',
        },
        scrollView: {
            flex: 1,
        },
        photoSection: {
            alignItems: 'center',
            paddingVertical: 32,
            backgroundColor: Colors.background,
            marginBottom: 16,
        },
        photoContainer: {
            width: 100,
            height: 100,
            borderRadius: 50,
            overflow: 'hidden',
            backgroundColor: '#F3F4F6',
            borderWidth: 2,
            borderColor: '#E5E7EB',
            borderStyle: 'dashed',
        },
        profileImage: {
            width: '100%',
            height: '100%',
        },
        photoPlaceholder: {
            width: '100%',
            height: '100%',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#F9FAFB',
        },
        photoPlaceholderText: {
            fontSize: 14,
            color: '#6B7280',
            marginTop: 12,
        },
        formContainer: {
            backgroundColor: '#FFFFFF',
            borderTopLeftRadius: 30,
            borderTopRightRadius: 30,
            shadowColor: '#171A1F',
            shadowOffset: {
                width: 0,
                height: 0,
            },
            shadowOpacity: 0.07,
            shadowRadius: 2,
            elevation: 4,
        },
        section: {
            backgroundColor: '#FFFFFF',
            marginBottom: 2,
            paddingVertical: 4,
        },
        sectionHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 20,
            marginBottom: 10,
        },
        sectionTitle: {
            fontSize: 16,
            fontWeight: '600',
            color: Colors.primary,
            marginLeft: 8,
        },
        inputContainer: {
            paddingHorizontal: 20,
            marginBottom: 20,
        },
        input: {
            backgroundColor: '#F9FAFB',
            borderRadius: 8,
            paddingHorizontal: 16,
            paddingVertical: 12,
            fontSize: 16,
            color: '#1F2937',
            borderWidth: 1,
            borderColor: '#E5E7EB',
        },
        inputError: {
            borderColor: '#EF4444',
        },
        dropdownWrapper: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: '#F9FAFB',
            borderWidth: 1,
            borderColor: '#E5E7EB',
            borderRadius: 8,
            paddingHorizontal: 16,
            paddingVertical: 12,
        },
        dropdownPlaceholder: {
            flex: 1,
            fontSize: 16,
            color: '#9CA3AF',
            marginLeft: 6,
        },
        dropdownSelected: {
            color: '#171A1FFF',
        },
        dropdownList: {
            backgroundColor: '#fff',
            borderWidth: 1,
            borderColor: '#BCC1CAFF',
            borderRadius: 8,
            marginTop: 2,
            zIndex: 100,
            position: 'absolute',
            left: 20,
            right: 20,
            top: 45,
        },
        dropdownListItem: {
            padding: 14,
            borderBottomWidth: 1,
            borderBottomColor: '#F3F4F6',
        },
        dropdownListItemText: {
            fontSize: 16,
            color: '#1F2937',
        },
        overlay: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            zIndex: 99,
        },
        errorText: {
            fontSize: 12,
            color: '#EF4444',
            marginTop: 4,
            marginLeft: 4,
        },
        workingHoursContainer: {
            paddingHorizontal: 20,
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: 8,
            marginBottom: 10,
        },
        workingHourButton: {
            paddingVertical: 8,
            paddingHorizontal: 16,
            borderRadius: 20,
            backgroundColor: '#F3F4F6',
        },
        workingHourButtonSelected: {
            backgroundColor: '#EEF2FF',
        },
        workingHourText: {
            fontSize: 14,
            color: '#6B7280',
            fontWeight: '500',
        },
        workingHourTextSelected: {
            color: '#6366F1',
            fontWeight: '600',
        },
        rowInputs: {
            flex: 1,
            flexDirection: 'row',
            paddingHorizontal: 20,
            gap: 8,
            marginBottom: 18,
        },
        halfInput: {
            flex: 1,
        },
        updateButton: {
            backgroundColor: Colors.primary,
            marginHorizontal: 20,
            marginTop: 0, // Remove marginTop for fixed button
            paddingVertical: 16,
            borderRadius: 12,
            alignItems: 'center',
            shadowColor: '#6366F1',
            shadowOffset: {
                width: 0,
                height: 4,
            },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            elevation: 8,
        },
        updateButtonText: {
            color: '#FFFFFF',
            fontSize: 16,
            fontWeight: '600',
        },
        bottomSpacer: {
            height: 40,
        },
        fixedButtonContainer: {
            position: 'absolute',
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: '#fff',
            paddingBottom: 20,
            paddingTop: 12,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: -4 },
            shadowOpacity: 0.12,
            shadowRadius: 12,
            elevation: 16,
            zIndex: 200,
        },
    });
}