import { Colors } from '@/constants/Colors';
import { StyleSheet } from 'react-native';
export const employeeListScreenStyles = () => {
    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: Colors.background,
        },
        header: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: 20,
            paddingTop: 44,
            backgroundColor: '#FFFFFF',
        },
        headerTitle: {
            fontSize: 18,
            fontWeight: 'bold',
            color: '#1F2937',
            flex: 1,
            textAlign: 'center',
            marginLeft: 64,
        },
        notificationButton: {
            padding: 8,
            marginRight: 12,
        },
        profileAvatar: {
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: Colors.primary,
            alignItems: 'center',
            justifyContent: 'center',
        },
        profileAvatarText: {
            color: '#FFFFFF',
            fontSize: 16,
            fontWeight: '600',
        },
        searchContainer: {
            paddingHorizontal: 20,
            paddingVertical: 12,
            borderBottomWidth: 1,
            borderBottomColor: '#e5e7eb',
            backgroundColor: '#FFFFFF',
        },
        searchInputContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: '#F7F7F780',
            borderRadius: 10,
            paddingHorizontal: 12,
            gap: 6,
            borderColor: '#EBEBEA99',
            borderWidth: 1,
        },
        searchInput: {
            flex: 1,
            fontSize: 16,
            color: '#1F2937',
            backgroundColor: '#F7F7F780'
        },
        selectAllContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 20,
            paddingVertical: 10,
            marginLeft: 9,
        },
        selectAllButton: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        selectAllText: {
            fontSize: 16,
            color: '#374151',
            fontWeight: '500',
        },
        employeeList: {
            flex: 1,
            marginHorizontal: 10,
        },
        employeeCard: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 20,
            paddingVertical: 14,
            marginHorizontal: 8,
            borderRadius: 8,
            marginBottom: 10,
            backgroundColor: '#FFFFFF',
            boxShadow: '0px 0px 1px #171a1f12, 0px 0px 2px #171a1f1F'
        },
        checkbox: {
            width: 20,
            height: 20,
            marginRight: 16,
            borderRadius: 4,
        },
        avatar: {
            width: 48,
            height: 48,
            borderRadius: 24,
            marginRight: 16,
        },
        avatarPlaceholder: {
            width: 48,
            height: 48,
            borderRadius: 24,
            marginRight: 16,
            alignItems: 'center',
            justifyContent: 'center',
        },
        avatarText: {
            color: '#FFFFFF',
            fontSize: 18,
            fontWeight: '600',
        },
        employeeInfo: {
            flex: 1,
        },
        employeeName: {
            fontSize: 16,
            fontWeight: '600',
            color: '#1F2937',
            marginBottom: 4,
        },
        employeePosition: {
            fontSize: 14,
            color: '#6B7280',
        },
        actionButtons: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: 8,
            width: 120,
        },
        actionButton: {
            padding: 5,
            borderRadius: 6,
            marginLeft: 6,
        },
        fab: {
            position: 'absolute',
            right: 20,
            bottom: 30,
            width: 56,
            height: 56,
            borderRadius: 28,
            backgroundColor: Colors.primary,
            alignItems: 'center',
            justifyContent: 'center',
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.25,
            shadowRadius: 3.84,
            elevation: 5,
        },
        // Skeleton Styles
        skeletonCheckbox: {
            width: 20,
            height: 20,
            backgroundColor: '#E5E7EB',
            borderRadius: 4,
            marginRight: 16,
        },
        skeletonAvatar: {
            width: 48,
            height: 48,
            backgroundColor: '#E5E7EB',
            borderRadius: 24,
            marginRight: 16,
        },
        skeletonName: {
            height: 16,
            backgroundColor: '#E5E7EB',
            borderRadius: 4,
            marginBottom: 8,
            width: '70%',
        },
        skeletonPosition: {
            height: 14,
            backgroundColor: '#E5E7EB',
            borderRadius: 4,
            width: '50%',
        },
        skeletonActionButton: {
            width: 26,
            height: 26,
            backgroundColor: '#E5E7EB',
            borderRadius: 6,
        },
        skeletonSelectAllText: {
            height: 16,
            backgroundColor: '#E5E7EB',
            borderRadius: 4,
            width: 80,
            marginLeft: 8,
        },
    });
};