import { Colors } from '@/constants/Colors';
import { StyleSheet } from 'react-native';
export const employeeDetailsScreenStyles = () => {
    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: Colors.background,
            paddingTop: 20,
        },
        header: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingHorizontal: 20,
            paddingVertical: 14,
            backgroundColor: '#fff',
            borderBottomWidth: 1,
            borderBottomColor: '#e5e7eb',
        },
        backButton: {
            padding: 4,
        },
        headerTitle: {
            fontSize: 18,
            fontFamily: 'Inter-SemiBold',
            color: '#111827',
        },
        headerActions: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 16,
        },
        avatar: {
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: Colors.primary,
            justifyContent: 'center',
            alignItems: 'center',
        },
        avatarText: {
            color: '#FFFFFF',
            fontSize: 16,
            fontWeight: '600',
        },
        placeholder: {
            width: 32,
        },
        content: {
            flex: 1,
        },
        employeeSection: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: '#fff',
            marginHorizontal: 20,
            marginTop: 16,
            borderRadius: 12,
            padding: 20,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 3,
        },
        employeeAvatar: {
            width: 60,
            height: 60,
            borderRadius: 30,
            marginRight: 16,
        },
        employeeInfo: {
            flex: 1,
        },
        employeeName: {
            fontSize: 20,
            fontFamily: 'Inter-SemiBold',
            color: '#111827',
            marginBottom: 4,
        },
        employeeDesignation: {
            fontSize: 16,
            fontFamily: 'Inter-Regular',
            color: '#6b7280',
        },
        summarySection: {
            backgroundColor: '#fff',
            marginHorizontal: 20,
            marginTop: 16,
            borderRadius: 12,
            padding: 20,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 3,
        },
        sectionTitle: {
            fontSize: 18,
            fontFamily: 'Inter-SemiBold',
            color: '#111827',
            marginBottom: 16,
        },
        summaryGrid: {
            flexDirection: 'row',
            justifyContent: 'space-between',
        },
        summaryCard: {
            flex: 1,
            alignItems: 'center',
            marginHorizontal: 4,
        },
        summaryIcon: {
            width: 40,
            height: 40,
            borderRadius: 20,
            justifyContent: 'center',
            alignItems: 'center',
            marginBottom: 8,
        },
        summaryValue: {
            fontSize: 14,
            fontFamily: 'Inter-SemiBold',
            color: '#111827',
            marginBottom: 4,
        },
        summaryLabel: {
            fontSize: 12,
            fontFamily: 'Inter',
            color: '#6b7280',
            textAlign: 'center',
        },
        monthSection: {
            backgroundColor: '#fff',
            marginHorizontal: 20,
            marginTop: 16,
            borderRadius: 12,
            padding: 16,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 3,
        },
        monthHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
        },
        monthText: {
            fontSize: 14,
            fontFamily: 'Inter-SemiBold',
            color: '#636AE8FF',
            padding: 6,
            paddingHorizontal: 10,
            borderRadius: 14,
            backgroundColor: Colors.primaryLight,
        },
        attendanceSection: {
            paddingHorizontal: 20,
            paddingTop: 16,
            paddingBottom: 20,
        },
        attendanceCard: {
            backgroundColor: '#fff',
            borderRadius: 12,
            padding: 16,
            marginBottom: 12,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 3,
            borderLeftWidth: 6,
            paddingTop: 8,
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            flex: 1,
        },
        dateSection: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            flex: 1,
        },
        dateText: {
            color: '#fff',
            fontSize: 14,
            fontFamily: 'Inter-SemiBold',
        },
        dayInfo: {

        },
        dayText: {
            fontSize: 12,
            fontFamily: 'Inter-Medium',
            color: '#8C8D8BFF',
        },
        statusBadge: {
            paddingHorizontal: 12,
            paddingVertical: 4,
            borderRadius: 12,
        },
        statusText: {
            color: '#fff',
            fontSize: 12,
            fontFamily: 'Inter-Medium',
        },
        timeSection: {
            paddingTop: 12,
        },
        timeRow: {
            flexDirection: 'column',
            justifyContent: 'space-between',
            marginBottom: 8,
            gap: 6,
        },
        timeItem: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
        },
        timeLabel: {
            fontSize: 14,
            fontFamily: 'Inter-Regular',
            color: '#6b7280',
            marginRight: 8,
        },
        timeValue: {
            fontSize: 14,
            fontFamily: 'Inter-Medium',
            color: '#111827',
        },
        workingHoursRow: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        workingHoursText: {
            fontSize: 14,
            fontFamily: 'Inter-Medium',
            color: '#6b7280',
            marginLeft: 8,
        },
    });
};